version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: superheroes
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/superheroes
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  fetch_superheroes:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - app
